### ISSUE TITLE
The preview_url in the response of `createVoiceFromPreview` is null, even though it's [required]

### ISSUE THREAD

**Issue by alexstyl** [elevenlabs/elevenlabs-js#101]
[The docs](https://elevenlabs.io/docs/api-reference/ttv-create-voice-from-preview) say that the response of `/v1/text-to-voice/create-previews` has a (required) `preview_url`. 

However, when I run the following code, the `preview_url` is always null.

```javascript
const response = await elevenLabsClient.textToVoice.createVoiceFromPreview({
            voice_name: name,
            voice_description: voice_description,
            generated_voice_id: voice_id
        })
response.preview_url
```

I think this is a bug, given the [required] label on the docs. Can you clarify?

**Comment by louisjoecodes** [comment]
Fixed this - thanks for flagging.
