### ISSUE TITLE
Is it possible to kill a stream?

### ISSUE THREAD

**Issue by dcporter44** [elevenlabs/elevenlabs-js#107]
I'm using the `stream` function as done in the README: 

```js
const audioStream = await elevenlabs.generate({
    stream: true,
    voice: "Bella",
    text: "This is a... streaming voice",
    model_id: "eleven_multilingual_v2",
});

stream(audioStream);
```

For my use case, it's possible that another stream starts while the other one is still playing. I have tried using `audioStream.destroy()` and `audioStream.pause()` but neither seem to do anything. Any advice appreciated!

**Comment by dsinghvi** [comment]
@dcporter44 you should be able to pass in abort controller to do via `RequestOptions`
