### ISSUE TITLE
Serious issues when generating speeches for German language

### ISSUE THREAD

**Issue by itinance** [elevenlabs/elevenlabs-js#21]
Several issues appear when generating speeches for the German language: 

- In German texts, numbers and dates will ALWAYS be spoken in English
- In German texts, English names and English words, that actually should be spoken in English and pronounced that way, were spoken in German, which sounds weird
- when too many non-german words occur within a sentence, like French names, the speaker turns into English dialect
- the same happens the longer a text is

It would be necessary to provide the target language as a specific setting to "tell" the models which language to be expected. Auto classification of the underlying language doesn't work at the moment and probably can't work in the long term thanks to the integration of English words and names naturally in other native languages (anglicisms).

**Comment by dsinghvi** [comment]
@itinance Elevenlabs now supports specifying target language, please reopen this issue if that no longer works for your usecase!
