### ISSUE TITLE
Feature request - timestamp with voice generation

### ISSUE THREAD

**Issue by bhanuc** [elevenlabs/elevenlabs-js#45]
Request to support the `https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}/with-timestamps` endpoint from sdk

**Comment by dsinghvi** [comment]
@bhanuc this will be released this week, ill follow up when its live

**Comment by 1lyad** [comment]
@dsinghvi any updates here?

**Comment by dsinghvi** [comment]
@bhanuc @1lyad @Gustqve this should be released, let me know if you have any issues!
