### ISSUE TITLE
Dubbing: Receiving target language empty even though sending a target language

### ISSUE THREAD

**Issue by asafchn** [elevenlabs/elevenlabs-js#54]
Issue
Using the dubbing api i'm receiving a 400 error that my request is missing the target_lang even though it is provided

Expected
pretty straightforward, the targetlanguage should work

Example code
```
const response = await elevenlabs.dubbing.dubAVideoOrAnAudioFile({
      mode: "automatic",
      source_lang: "en",
      target_lang: "de",
      file: video,
    });
```

and the response:
<img width="1175" alt="image" src="https://github.com/elevenlabs/elevenlabs-js/assets/87265670/2123407b-be66-403f-98a6-7448383c9909">

**Comment by dsinghvi** [comment]
@asafchn do you mind trying the request via cURL and confirming that the API doesn't throw? We would love to narrow whether or not the error is specific to the SDK

**Comment by brainvine** [comment]
Same issue here:
Error during dubbing request: {
  detail: {
    status: 'empty_target_language',
    message: 'Target language must be set in automatic dubbing mode. Either set the target language or set dubbing studio to true.'
  }
}
 POST /api/tools/video-dubbing 500 in 220ms

Not using the SDK, but direct API call in NextJS. This only happens on "URL" mode, not on the file-upload.

**Comment by dsinghvi** [comment]
@lharries it looks like the user is saying that this doesn't work in the raw API

**Comment by Mgonand** [comment]
Same error here, also using `source_url`. Curl works perfect but all of this are failing with this error for me:
- Javascript SDK
- Native fetch (form-data and JSON)
- npm node-fetch (form-data and JSON)

In form-data (multipart/form-data) the error is different: "Missing boundary in multipart"

Hope it help with the debug because it looks like is an API issue.

**Comment by dsinghvi** [comment]
Thanks for bearing with us folks, we've tested and things are looking good on version `0.8.2`.
