### ISSUE TITLE
Accessing Legacy Voices via the API

### ISSUE THREAD

**Issue by probityrules** [elevenlabs/elevenlabs-js#66]
Is it possible to access legacy voices via the API? I'm getting an unnumbered error back for several voices: `Error: [voice name] is not a valid voice name`, but these are showing up on the ElevenLabs website as "(Legacy)". I can start using the newer voices at some point, but wanted to finish up a few things with the original voices first if they're still available.

**Comment by dsinghvi** [comment]
@probityrules this is fixed in `0.11.0`!

**Comment by probityrules** [comment]
@dsinghvi Will `generate` automatically accept legacy voices or do I need to send some sort of parameter? Currently, it's no longer throwing an error, but I am getting a empty/invalid MP3's instead.
