### ISSUE TITLE
Issues with some missing exports

### ISSUE THREAD

**Issue by BolajiAyodeji** [elevenlabs/elevenlabs-js#7]
Hi! Thanks for creating a JS equivalent of the Python SDK.

I was giving it a quick spin and tried to test in a local TypeScript environment but kept getting the error: `Module '"elevenlabs"' has no exported member 'play'`. The same applies to `stream`.

<img width="946" alt="Screenshot 2024-01-29 at 09 54 34" src="https://github.com/elevenlabs/elevenlabs-js/assets/30334776/38652ebd-9c87-4565-8733-b7f97654a498">

For the `apiKey` argument:

<img width="792" alt="Screenshot 2024-01-29 at 09 55 23" src="https://github.com/elevenlabs/elevenlabs-js/assets/30334776/0ad31343-8743-46c9-8be1-d013950712ed">

Even the `generate` property does not exist:

<img width="1063" alt="Screenshot 2024-01-29 at 09 56 41" src="https://github.com/elevenlabs/elevenlabs-js/assets/30334776/b347fc5c-054c-4047-b029-d7c890f0e885">

---

The same error occurs even when the SDK is imported into a Reactjs environment. Is there something I'm missing or some type definitions we need to install for the SDK? Everything seems to be set up correctly on my end.

**Comment by BolajiAyodeji** [comment]
Could you help here, please, @dsinghvi? Any thoughts?

**Comment by dsinghvi** [comment]
@BolajiAyodeji thanks for tagging me directly -- the SDK has been regenerated and we have published `0.1.3`. You should see the correct exports come through in the SDK. Feel free to reopen up this issue if you still have problems!
