### ISSUE TITLE
High latency using this SDK vs HTTPs call

### ISSUE THREAD

**Issue by Sheldenshi** [elevenlabs/elevenlabs-js#74]
Average firstArrive for Elevenlabs HTTP: 756.60 ms
Average latency for Elevenlabs HTTP: 1088.60 ms

Average firstArrive for Elevenlabs SDK: 776.50 ms
Average latency for Elevenlabs SDI: 1149.30 ms

**Comment by dsinghvi** [comment]
@Sheldenshi  it looks like roughly 20-40 ms of latency are being added, which is in the expected range.
