### ISSUE TITLE
Example code is not working

### ISSUE THREAD

**Issue by 0xfce** [elevenlabs/elevenlabs-js#75]
Im getting the following error when trying to test the example code in the README.md
[INFO] 11:34:40 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.2, typescript ver. 5.5.4)
TypeError: o[Symbol.iterator] is not a function
    at __asyncValues (a:\test\node_modules\elevenlabs\wrapper\play.js:14:98)
    at a:\test\node_modules\elevenlabs\wrapper\play.js:46:28
    at Generator.next (<anonymous>)
    at a:\test\node_modules\elevenlabs\wrapper\play.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (a:\test\node_modules\elevenlabs\wrapper\play.js:4:12)
    at play (a:\test\node_modules\elevenlabs\wrapper\play.js:31:12)
    at a:\test\src\main.ts:25:15
    at Generator.next (<anonymous>)
    at fulfilled (a:\test\src\main.ts:5:58)
    
   this is the code
   const textToSpeech = async(text:String, voiceId:String) => {
    const audio = await eleven.generate({
        voice: voiceId as string,
        text: text as string,
        model_id: "eleven_monolingual_v2"
    });
    await play(audio);
}

textToSpeech("Hello World, this is just a text for the api i guess", MASCULINE);

**Comment by RohinBhargava** [comment]
Hi, we have flagged this, and we should have a fix on Monday pushed out. Thank you for bringing to our attention!

**Comment by dsinghvi** [comment]
@0xfce This is fixed in `v0.14.0`, please let us know if you still have issues!

**Comment by 0xfce** [comment]
Hi, when using model_id of "eleven_monolingual_v2" i get the following error
ElevenLabsError: Status code: 400
Body: {
  "readableStream": {},
  "reader": {},
  "events": {
    "data": [],
    "end": [],
    "error": [],
    "readable": [],
    "close": [],
    "pause": [],
    "resume": []
  },
  "paused": false,
  "resumeCallback": null,
  "encoding": null
}
    at TextToSpeech.<anonymous> (a:\test\node_modules\elevenlabs\api\resources\textToSpeech\client\Client.js:110:31)
    at Generator.next (<anonymous>)
    at fulfilled (a:\test\node_modules\elevenlabs\api\resources\textToSpeech\client\Client.js:31:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 400,
  body: Node18UniversalStreamWrapper {
    readableStream: ReadableStream { locked: true, state: 'readable', supportsBYOB: false },
    reader: ReadableStreamDefaultReader {
      stream: ReadableStream { locked: true, state: 'readable', supportsBYOB: false },
      readRequests: 0,
      close: Promise { <pending> }
    },
    events: {
      data: [],
      end: [],
      error: [],
      readable: [],
      close: [],
      pause: [],
      resume: []
    },
    paused: false,
    resumeCallback: null,
    encoding: null
  }
}
but when i use the v1 version it works perfectly!
