### ISSUE TITLE
Type in function name client.textToSpeech.convertWithTimstamps

### ISSUE THREAD

**Issue by kdstew** [elevenlabs/elevenlabs-js#79]
I think `client.textToSpeech.convertWithTimstamps` should be `client.textToSpeech.convertWithTimestamps`.

**Comment by dsinghvi** [comment]
@kdstew  this is fixed in the latest releasem`0.15.0`! Thanks for bringing this to our attention

**Comment by kdstew** [comment]
Thank you, @dsinghvi!
