### ISSUE TITLE
Timestamps is Spelled 'Timstamps' in the codebase

### ISSUE THREAD

**Issue by cloudbring** [elevenlabs/elevenlabs-js#81]
Every time I see it in my code, I think I'm hallucinating.

Github Search: https://github.com/search?q=repo%3Aelevenlabs%2Felevenlabs-js%20timstamp&type=code

![image](https://github.com/user-attachments/assets/5c1c2ae0-b367-4bf5-8660-ddd86be886fa)

**Comment by dsinghvi** [comment]
@cloudbring this is fixed in the latest releasem`0.15.0`! Thanks for bringing this to our attention
