### ISSUE TITLE
ElevenLabsError: this.readableStream.getReader is not a function

### ISSUE THREAD

**Issue by TowhidKashem** [elevenlabs/elevenlabs-js#84]
Hi,

Just trying to run a very basic example in node but running into this error:

```
ElevenLabsError: this.readableStream.getReader is not a function
    at TextToSpeech.<anonymous> (/Users/redacted/Desktop/node_modules/elevenlabs/api/resources/textToSpeech/client/Client.js:125:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/redacted/Desktop/node_modules/elevenlabs/api/resources/textToSpeech/client/Client.js:31:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Non-zero exit: code 1, signal null
```

**eleven-test.mjs:**

```
import { ElevenLabs, ElevenLabsClient } from 'elevenlabs';

const elevenlabs = new ElevenLabsClient({
  apiKey: 'REDEACTED'
});

const audio = await elevenlabs.generate({
  text: 'the quick brown fox jumped over some lazy dog',
  model_id: 'eleven_multilingual_v2',
  voice: 'Rachel',
  language_code: 'en-US',
  output_format: ElevenLabs.OutputFormat.Mp32205032,
  optimize_streaming_latency: ElevenLabs.OptimizeStreamingLatency.Zero
});

console.log({ audio });
```

running it from the terminal like:

> node eleven-test.mjs

**Comment by RohinBhargava** [comment]
Hi Towhid! In my tests, the voice ID ended up being an issue that led to an error. Rachel's voice ID is `21m00Tcm4TlvDq8ikWAM`, and I found it here: 
<img width="1467" alt="Screenshot 2024-08-26 at 11 00 00 PM" src="https://github.com/user-attachments/assets/d74384b1-fa3b-448a-9138-7f90e5181c02">

Can you please try this and see if the API works? I understand this is suboptimal UX, and if that's the fix, I will make sure that we track better error messages from the client!

**Comment by TowhidKashem** [comment]
> Hi Towhid! In my tests, the `language_code` parameter ended up being an issue that led to an error. 
> 
> 
> 
> I see this in the source code: https://github.com/elevenlabs/elevenlabs-js/blob/da57b8790e985de26ab27ed6acab0c9f854aaa97/src/api/resources/textToSpeech/client/requests/TextToSpeechRequest.ts#L37C9-L37C207
> 
> 
> 
> Can you please try to either change the model being used or remove the parameter and see if the API works? I understand this is suboptimal UX, and if that's the fix, I will make sure that we track better error messages from the client, and have better examples!

I ended up using the rest api, but before that had tried various things including removing those additional optional options and had the same issue. Anyway if it's not happening for you consider it closed.

**Comment by aymenitc** [comment]
I'm having the exact error. How did you mange to solve it:
```const audioStream = await clientTTS.generate({
    stream: true,
    voice_id: 'EXAVITQu4vr4xnSDxMaL',
    text: dataText2,
    model_id: 'eleven_multilingual_v2',
  //  optimize_streaming_latency: OptimizeStreamingLatency.Three,
    voice_settings: {
      stability: 0.7,
      similarity_boost: 1.0,
      style: 0.5,
      use_speaker_boost: true
    }
  })```

**Comment by PaulAsjes** [comment]
@aymenitc can you try using the stream method directly?

```
const audioStream = await client.textToSpeech.convertAsStream("EXAVITQu4vr4xnSDxMaL", {
    text: dataText2,
    model_id: "eleven_multilingual_v2",
    voice_settings: {
      stability: 0.7,
      similarity_boost: 1.0,
      style: 0.5,
      use_speaker_boost: true
    }
});
```
