### ISSUE TITLE
Conversational AI history

### ISSUE THREAD

**Issue by Ishan5hrestha** [elevenlabs/elevenlabs-js#97]
I have implemented conversational AI on a website, but to view what the users are talking about with the AI, I have to login to ElevenLabs dashboard. Is there no API that I can use to directly view the conversation data? I could find any references here:
https://elevenlabs.io/docs/api-reference/conversational-ai

**Comment by najmiter** [comment]
same with this endpoint: https://elevenlabs.io/docs/api-reference/get-generated-items

it gives an empty list every time

```js
{
  "history": [],
  "last_history_item_id": null,
  "has_more": false
}
```

and also getting an individual item doesn't work either (https://elevenlabs.io/docs/api-reference/get-history-item-by-id)

says:

```js
{
  "detail": {
    "status": "invalid_id",
    "message": "A history item with ID 'JRNGXs63ikgFHx1Rb8ME' was not found on the server."
  }
}
```

**Comment by najmiter** [comment]
after looking at their app in the browser and the network tab, they were using this endpoint to get the data, and it worked on my server as well.

```js
`https://api.elevenlabs.io/v1/convai/conversations/${conversation_id}`
```

the following is the complete snippet:

```js
const requestHeaders: HeadersInit = new Headers();
requestHeaders.set('xi-api-key', XI_API_KEY!);

const fetchResponse = await fetch(
  `https://api.elevenlabs.io/v1/convai/conversations/${conversation_id}`,
  {
    method: 'GET',
    headers: requestHeaders,
  },
);
```

**Comment by Ishan5hrestha** [comment]
Wow, that works! Thank you so much man!
I do think they might change these endpoints after their launch, so might be bit risky to use on production apps.

**Comment by Ishan5hrestha** [comment]
Used the provided solution as the current quick fix solution until proper API is released.
